packages:
  - packages/*
  - packages/strapi/src/plugins/*
publicHoistPattern:
  - '*@strapi*'
  - lodash
  - lodash/**
allowBuilds:
  '@swc/core': true
  better-sqlite3: true
  core-js-pure: true
  esbuild: true
  '@parcel/watcher': false
  core-js: false
  sharp: false
